algoritmo "CONTADOR"

var
    contadorNegativo, contadorPositivo: inteiro
inicio

    contadorNegativo <- 10
    contadorPositivo <- 0



    enquanto (contadorNegativo >= 0) faca

        escreva (contadorNegativo, " ")
        contadorNegativo <- contadorNegativo - 1
    fimenquanto
    escreval(" ")
    escreval("------------")

     enquanto (contadorPositivo <= 10) faca

        escreva (contadorPositivo, " ")
        contadorPositivo <- contadorPositivo + 1

    fimenquanto

fimalgoritmo