algoritmo "Nome do Programa"

var

    contador,numero,zeroADez: inteiro

inicio
    
    

    para contador <- 1 ate 6 passo 1 faca
        
        escreval("Digite um número inteiro")
        leia(numero)

        se ((numero >= 0) e (numero <= 10)) entao
           zeroADez <- zeroADez + 1
        
        fimse
        

    fimPara

    escreval("foram: ", zeroADez ," que estão entre 0 e 10.")

fimalgoritmo


