algoritmo "procedimento soma"

var

    numero,dobro,a1,b1: inteiro

    procedimento Soma(a,b:inteiro)
        inicio
            escreval("Recebi o valor A: ",a)
            escreval("Recebi o valor B: ",b)
            escreval("A soma dos valores A + B = ",a+b)

        fimprocedimento


inicio
    escreval("Digite um valor inteiro: ")
    leia(a1)
    escreval("Digite outro valor inteiro: ")
    leia(b1)
    

    Soma(a1,b1)



fimalgoritmo