algoritmo "procedimento par impar"

var

    numeroUsuario:inteiro

procedimento testador(a:inteiro)
    inicio
        se a % 2 = 0 entao
            escreval("Esse número é PAR")
        senao
            escreval("Esse número é IMPAR") 
        fimse

    fimprocedimento


inicio
    escreval("Digite um valor inteiro: ")
    leia(numeroUsuario)
    

    Testador(numeroUsuario)
    

   



fimalgoritmo