algoritmo "Contagem"

var

    contador,valorFinal: inteiro

inicio

    escreval(" Digite um número inteiro para  o  Valor final: ")
    leia(valorFinal)

    para contador <- 6 ate valorFinal  faca

        escreval(contador)


        
    fimPara

    escreval("Acabou!")
    

fimalgoritmo



// 6)	Aprimore o algoritmo da questão 1, perguntando ao usuário quantas conversões serão realizadas.