algoritmo "procedimento Gerador"


var

procedimento Gerador()
    inicio
        escreval("+-------========-------+")
        escreval("       Olá mundo!       ")
        escreval("+-------========-------+")
    fimprocedimento

inicio

    Gerador()

fimalgoritmo










// 1) Crie um programa que tenha um procedimento Gerador() que, quando chamado, mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
// Ex: Ao chamar Gerador() aparece:
 
